[project]
name = "slt-quasi-singular"
version = "0.0.0"
description = "Small project for experimenting with quasi-singular SLT mixtures and examples"
readme = "README.md"
authors = [ { name = "Ashraf Ahmed" } ]
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "scipy_extensions"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
scipy_extensions = { workspace = true }
